// Departure airports offered in the flight search. Not exhaustive — guests can type anything,
// and unmatched text falls back to a Google Flights phrase search (see lib/flight-search.ts).
// `sky` is Skyscanner's place code when it differs from the IATA code (city-wide "all airports" entries).

export type Airport = { code: string; city: string; name: string; country: string; sky?: string };

const rows: Array<[code: string, city: string, name: string, country: string, sky?: string]> = [
  // United Kingdom & Ireland
  ["LON", "London", "All airports", "United Kingdom", "lond"],
  ["LHR", "London", "Heathrow", "United Kingdom"],
  ["LGW", "London", "Gatwick", "United Kingdom"],
  ["STN", "London", "Stansted", "United Kingdom"],
  ["LTN", "London", "Luton", "United Kingdom"],
  ["LCY", "London", "City", "United Kingdom"],
  ["MAN", "Manchester", "Manchester", "United Kingdom"],
  ["BHX", "Birmingham", "Birmingham", "United Kingdom"],
  ["EDI", "Edinburgh", "Edinburgh", "United Kingdom"],
  ["GLA", "Glasgow", "Glasgow", "United Kingdom"],
  ["ABZ", "Aberdeen", "Aberdeen", "United Kingdom"],
  ["NCL", "Newcastle", "Newcastle", "United Kingdom"],
  ["LBA", "Leeds", "Leeds Bradford", "United Kingdom"],
  ["LPL", "Liverpool", "John Lennon", "United Kingdom"],
  ["EMA", "Nottingham", "East Midlands", "United Kingdom"],
  ["BRS", "Bristol", "Bristol", "United Kingdom"],
  ["CWL", "Cardiff", "Cardiff", "United Kingdom"],
  ["SOU", "Southampton", "Southampton", "United Kingdom"],
  ["BFS", "Belfast", "International", "United Kingdom"],
  ["DUB", "Dublin", "Dublin", "Ireland"],
  ["ORK", "Cork", "Cork", "Ireland"],
  // Europe
  ["PAR", "Paris", "All airports", "France", "pari"],
  ["CDG", "Paris", "Charles de Gaulle", "France"],
  ["AMS", "Amsterdam", "Schiphol", "Netherlands"],
  ["BRU", "Brussels", "Brussels", "Belgium"],
  ["FRA", "Frankfurt", "Frankfurt", "Germany"],
  ["MUC", "Munich", "Munich", "Germany"],
  ["BER", "Berlin", "Brandenburg", "Germany"],
  ["DUS", "Düsseldorf", "Düsseldorf", "Germany"],
  ["HAM", "Hamburg", "Hamburg", "Germany"],
  ["VIE", "Vienna", "Vienna", "Austria"],
  ["ZRH", "Zurich", "Zurich", "Switzerland"],
  ["GVA", "Geneva", "Geneva", "Switzerland"],
  ["MAD", "Madrid", "Barajas", "Spain"],
  ["BCN", "Barcelona", "El Prat", "Spain"],
  ["LIS", "Lisbon", "Humberto Delgado", "Portugal"],
  ["FCO", "Rome", "Fiumicino", "Italy"],
  ["MXP", "Milan", "Malpensa", "Italy"],
  ["CPH", "Copenhagen", "Kastrup", "Denmark"],
  ["ARN", "Stockholm", "Arlanda", "Sweden"],
  ["OSL", "Oslo", "Gardermoen", "Norway"],
  ["HEL", "Helsinki", "Vantaa", "Finland"],
  ["WAW", "Warsaw", "Chopin", "Poland"],
  ["PRG", "Prague", "Václav Havel", "Czechia"],
  ["BUD", "Budapest", "Ferenc Liszt", "Hungary"],
  ["ATH", "Athens", "Eleftherios Venizelos", "Greece"],
  ["IST", "Istanbul", "Istanbul", "Türkiye"],
  // North America
  ["NYC", "New York", "All airports", "United States", "nyca"],
  ["JFK", "New York", "John F. Kennedy", "United States"],
  ["EWR", "Newark", "Liberty", "United States"],
  ["BOS", "Boston", "Logan", "United States"],
  ["IAD", "Washington, D.C.", "Dulles", "United States"],
  ["BWI", "Baltimore", "Baltimore/Washington", "United States"],
  ["PHL", "Philadelphia", "Philadelphia", "United States"],
  ["ATL", "Atlanta", "Hartsfield-Jackson", "United States"],
  ["ORD", "Chicago", "O'Hare", "United States"],
  ["DTW", "Detroit", "Metropolitan", "United States"],
  ["MSP", "Minneapolis", "Saint Paul", "United States"],
  ["IAH", "Houston", "George Bush Intercontinental", "United States"],
  ["DFW", "Dallas", "Fort Worth", "United States"],
  ["MIA", "Miami", "Miami", "United States"],
  ["CLT", "Charlotte", "Douglas", "United States"],
  ["DEN", "Denver", "Denver", "United States"],
  ["LAX", "Los Angeles", "Los Angeles", "United States"],
  ["SFO", "San Francisco", "San Francisco", "United States"],
  ["SEA", "Seattle", "Tacoma", "United States"],
  ["YTO", "Toronto", "All airports", "Canada", "ytoa"],
  ["YYZ", "Toronto", "Pearson", "Canada"],
  ["YUL", "Montreal", "Trudeau", "Canada"],
  ["YOW", "Ottawa", "Macdonald-Cartier", "Canada"],
  ["YYC", "Calgary", "Calgary", "Canada"],
  ["YEG", "Edmonton", "Edmonton", "Canada"],
  ["YVR", "Vancouver", "Vancouver", "Canada"],
  ["YWG", "Winnipeg", "Winnipeg", "Canada"],
  ["YHZ", "Halifax", "Stanfield", "Canada"],
  // Africa
  ["ABV", "Abuja", "Nnamdi Azikiwe", "Nigeria"],
  ["PHC", "Port Harcourt", "Port Harcourt", "Nigeria"],
  ["KAN", "Kano", "Mallam Aminu Kano", "Nigeria"],
  ["ENU", "Enugu", "Akanu Ibiam", "Nigeria"],
  ["QUO", "Uyo", "Victor Attah", "Nigeria"],
  ["CBQ", "Calabar", "Margaret Ekpo", "Nigeria"],
  ["BNI", "Benin City", "Benin", "Nigeria"],
  ["QOW", "Owerri", "Sam Mbakwe", "Nigeria"],
  ["ACC", "Accra", "Kotoka", "Ghana"],
  ["ABJ", "Abidjan", "Félix Houphouët-Boigny", "Côte d’Ivoire"],
  ["DSS", "Dakar", "Blaise Diagne", "Senegal"],
  ["DLA", "Douala", "Douala", "Cameroon"],
  ["NBO", "Nairobi", "Jomo Kenyatta", "Kenya"],
  ["ADD", "Addis Ababa", "Bole", "Ethiopia"],
  ["KGL", "Kigali", "Kigali", "Rwanda"],
  ["JNB", "Johannesburg", "O. R. Tambo", "South Africa"],
  ["CPT", "Cape Town", "Cape Town", "South Africa"],
  ["CAI", "Cairo", "Cairo", "Egypt"],
  ["CMN", "Casablanca", "Mohammed V", "Morocco"],
  // Middle East, Asia & Pacific
  ["DXB", "Dubai", "Dubai", "United Arab Emirates"],
  ["AUH", "Abu Dhabi", "Zayed", "United Arab Emirates"],
  ["DOH", "Doha", "Hamad", "Qatar"],
  ["RUH", "Riyadh", "King Khalid", "Saudi Arabia"],
  ["JED", "Jeddah", "King Abdulaziz", "Saudi Arabia"],
  ["DEL", "Delhi", "Indira Gandhi", "India"],
  ["BOM", "Mumbai", "Chhatrapati Shivaji", "India"],
  ["SIN", "Singapore", "Changi", "Singapore"],
  ["HKG", "Hong Kong", "Hong Kong", "Hong Kong"],
  ["KUL", "Kuala Lumpur", "Kuala Lumpur", "Malaysia"],
  ["SYD", "Sydney", "Kingsford Smith", "Australia"],
  ["MEL", "Melbourne", "Tullamarine", "Australia"],
  ["PER", "Perth", "Perth", "Australia"],
];

export const airports: Airport[] = rows.map(([code, city, name, country, sky]) => ({ code, city, name, country, sky }));

// "London — All airports (LON)" / "Manchester (MAN)" when the airport is simply named after its city.
export function airportLabel(airport: Airport) {
  return airport.name === airport.city ? `${airport.city} (${airport.code})` : `${airport.city} — ${airport.name} (${airport.code})`;
}
